### PR TITLE
fix: add debug labels to form and field atoms

### LINKED ISSUE #40: Set debug labels for the form atoms
To simplify debugging, the [atom debug labels](https://jotai.org/docs/guides/debugging#debug-labels) can be used.

Currently all the atoms are unlabeled.
image

With labeling, it can be easy to navigate & explore the form data:
image

Code can be as simple as:
https://github.com/MiroslavPetrik/form-atoms-field/commit/2d4342062b251850e157d19daec58817c6884b37

### PR DESCRIPTION
**Pull request by MiroslavPetrik**
Closes #40

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -327,7 +327,15 @@ export function formAtom<Fields extends FormFields>(
     submitStatus: submitResultAtom,
     submitCount: submitCountAtom,
     reset: resetAtom,
-  });
+  };
+
+  if (process.env.NODE_ENV !== "production") {
```
Comment (jaredLunde) [inline src/index.tsx:332]: Think you'll want to do
```suggestion
  if (typeof process !== "undefined" && process.env.NODE_ENV !== "production") {
```
 To avoid breaking bundles without a process polyfill

**Review by jaredLunde — CHANGES_REQUESTED** [review]
One small thing

File: src/index.tsx [hunk 2]
```diff
@@ -645,9 +653,16 @@ export function fieldAtom<Value>(
     reset: resetAtom,
     ref: refAtom,
     _initialValue: initialValueAtom,
-    _validateCallback: config.validate,
     _validateCount: validateCountAtom,
-  });
+  };
+
+  if (process.env.NODE_ENV !== "production") {
```
Comment (jaredLunde) [inline src/index.tsx:659]: Same here

File: src/index.tsx (hunk 1 above)
Comment (MiroslavPetrik) [reply src/index.tsx]: fixed https://github.com/jaredLunde/form-atoms/pull/43/commits/85e0272688d08f45a3d3635e8a7c052e75feced3
